import flor from '../assets/flor.png';

export const existingProducts = [
  {
    id: 1,
    name: 'Rosa Roja',
    basePrice: 250,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 24,
    img: flor,
    lastUpdated: '2026-01-20T10:15:00Z',
    updatedBy: 'Lluvia',
    isActive: true,
    stock: 50
  },
  {
    id: 2,
    name: 'Tulipán Amarillo',
    basePrice: 180,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 20,
    img: flor,
    lastUpdated: '2026-01-19T14:30:00Z',
    updatedBy: 'Ivan',
    isActive: true,
    stock: 40
  },
  {
    id: 3,
    name: 'Margarita Blanca',
    basePrice: 120,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 30,
    img: flor,
    lastUpdated: '2026-01-18T09:45:00Z',
    updatedBy: 'Lluvia',
    isActive: true,
    stock: 60
  },
  {
    id: 4,
    name: 'Orquídea Púrpura',
    basePrice: 600,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 12,
    img: flor,
    lastUpdated: '2026-01-17T11:00:00Z',
    updatedBy: 'Ivan',
    isActive: true,
    stock: 25
  },
  {
    id: 5,
    name: 'Girasol',
    basePrice: 300,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 12,
    img: flor,
    lastUpdated: '2026-01-16T16:20:00Z',
    updatedBy: 'Lluvia',
    isActive: true,
    stock: 30
  },
  {
    id: 6,
    name: 'Lirio Azul',
    basePrice: 500,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 12,
    img: flor,
    lastUpdated: '2026-01-15T08:10:00Z',
    updatedBy: 'Ivan',
    isActive: true,
    stock: 20
  },
  {
    id: 7,
    name: 'Clavel Rosa',
    basePrice: 180,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 25,
    img: flor,
    lastUpdated: '2026-01-14T13:55:00Z',
    updatedBy: 'Lluvia',
    isActive: true,
    stock: 45
  },
  {
    id: 8,
    name: 'Hortensia',
    basePrice: 400,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 10,
    img: flor,
    lastUpdated: '2026-01-13T15:40:00Z',
    updatedBy: 'Ivan',
    isActive: true,
    stock: 15
  },
  {
    id: 9,
    name: 'Peonía',
    basePrice: 550,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 12,
    img: flor,
    lastUpdated: '2026-01-12T12:30:00Z',
    updatedBy: 'Lluvia',
    isActive: true,
    stock: 20
  },
  {
    id: 10,
    name: 'Dalia',
    basePrice: 220,
    currentPrice: 0,
    priceAdjustmentType: 'percentage',
    priceAdjustmentValue: 0,
    finalPrice: 0,
    packageSize: 20,
    img: flor,
    lastUpdated: '2026-01-11T10:05:00Z',
    updatedBy: 'Ivan',
    isActive: false,
    stock: 35
  }
];
